### PR TITLE
init frame and logger

### PR DESCRIPTION
**Pull request by robinlg**
init frame and logger

### CODE REVIEW

**Review by JimmyShi22 — APPROVED** [review]
LGTM

**Comment by robinlg** [comment]
I modified the logger structure. Here are some points to help you understand that.
1. I set glogger into the `internal.Logger` in glooger.go file. Thus all of functions about printing that will use google log's package actually.
2. I use componentData to add the name of micro-services in front of each log line. But function about printing will use google log's package actually.

**Comment by JimmyShi22** [comment]
Get it !! 👍 👍 👍 
Just push your code as you like and we will check them after all your work finished.

**Comment by leo201313** [comment]
Hi, I'm interested in this project. As using and learning golang for a while, I wanna know whether I could help you  to complete this project or say make it btter.

**Comment by robinlg** [comment]
> Hi, I'm interested in this project. As using and learning golang for a while, I wanna know whether I could help you to complete this project or say make it btter.

Of course you can commit your code whenever you like. I'm coding the part of client connection. You can offer your idea after I'm done that. Or you can fork a new branch from `WeCross-Go-SDK`. It's up to you :)

**Pull request merged**
