### PR TITLE
Backbone

### PR DESCRIPTION
**Pull request by leo201313**
This is the backbone of the WeCross-Go-SDK I thought. 
At the very beginning, I've initialized the error and status codes and a log system.
At next, I made out the data struct of Response, Request, Callback.
Then I've completed the management of http connections.
Now, I'm heading to realize the 'send' and 'asynsend' function of the WeCrossRPCService, which should chain the requests, responses and callback.
Though this project is mid-way, all need is just time.

### CODE REVIEW

**Comment by leo201313** [comment]
Now asyncSend and send functions of WeCrossRPCService have been realized.
Now I'm heading to realize the various responses and requests to make remote call. And then, this project is about to be finished.

**Comment by JimmyShi22** [comment]
Nice! We can see that the Go SDK is comming soon.
Are there any code is written by [RobinLG](https://github.com/RobinLG) in this PR #1 ?
For every developer should remember. Please pull from his repository and add your commit base on that. Thanks from all WeCross developer! 💯

**Comment by leo201313** [comment]
> Nice! We can see that the Go SDK is comming soon. Are there any code is written by [RobinLG](https://github.com/RobinLG) in this PR #1 ? For every developer should remember. Please pull from his repository and add your commit base on that. Thanks from all WeCross developer! 💯

Though RobinLG has made a good start, this branch contains no code of PR #1. It seems RoBinLG wants to make Go-SDK powerful enough to handle things that is even not resolved by WeCross-Java-SDK, so he is now adding balancing to client connection. 

However, for me I just want to make Go-SDK behave just like the Java one at this time. I focus on the data structure design of WeCrossRPCService and so the response, requests, and callback. To make my development process smoother, I also realize a log system and error process method that is similar as the Java one.

In the near future, after completion of this branch, I'll consider how to use RoBinLG's code to make Go-SDK much stable and useful.

**Comment by JimmyShi22** [comment]
Go it! We can make two branches for your code and [RobinLG](https://github.com/RobinLG)'s code(https://github.com/WeBankBlockchain/WeCross-Go-SDK/pull/1)

**Review by JimmyShi22 — APPROVED** [review]

**Pull request merged**
