### PR TITLE
finish all

### PR DESCRIPTION
**Pull request by leo201313**
Now I've finished things about accounts.

### CODE REVIEW

**Comment by leo201313** [comment]
@JimmyShi22 hi, I've almost finished the  WeCross-Go-SDK after completing the remote calls one by one. Now I'm thinking a way to realize functions that "TransactionalAopHandler" done (about XATransaction) in a Golang manner. After that, I'll go ahead to do tests of the RPC server. 

I wonder whether there are some existed infrastructures that may be helpful  for testing a go SDK. As there now lacks WeCross-Console and WeCross-AccountManager written in Golang, I probobaly would go through a hard time to make all things right.

**Comment by leo201313** [comment]
It seems that AOP functions are not necessary in a go sdk, so I just skipped it.
The Go sdk now has all the functions just as the Java one does.
Some basic tests are done, but it is far away from completion. HELP is in need!
I'll add instructions of go-sdk into the WeCross document recently.

**Comment by leo201313** [comment]
I've done tests of the API functions one by one.
Now go-sdk can behave just like the java one and ready for the first release.

**Review by JimmyShi22 — APPROVED** [review]

**Comment by JimmyShi22** [comment]
膜拜！！

**Pull request merged**
